## Importing libraries

In [89]:
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.dummy import DummyRegressor
import pandas as pd
import html
import time
import csv
# from scrapy.downloadermiddlewares.retry import RetryMiddleware
# from scrapy_random_proxies.middlewares import RandomProxyMiddleware
import requests
from bs4 import BeautifulSoup
import random
from requests_ip_rotator import ApiGateway, EXTRA_REGIONS
import winsound
import os

## Dataset

#### First of all, we need to collect the data from CodeForces website
##### we will do this after simulating a login session

In [27]:
# Obtain the CSRF token from the login page
login_url = 'https://codeforces.com/enter'
session = requests.Session()
response = session.get(login_url)
soup = BeautifulSoup(response.content, 'html.parser')
csrf_token = soup.find('input', {'name': 'csrf_token'}).get('value')
# Specify your login credentials
username = 'roro_1999_hh@hotmail.com'
password = 'Dodehtree*-*19781987'

# Send a POST request with the login credentials and CSRF token
login_data = {
    'csrf_token': csrf_token,
    'action': 'enter',
    'handleOrEmail': username,
    'password': password,
    'remember': 'on'  # You can remove this line if you don't want to be remembered
}

session.post(login_url, data=login_data)

### Problemset

#### Problemset of the first page in problemset in codeforces

In [4]:
problemset_url = 'https://codeforces.com/problemset?order=BY_SOLVED_DESC'

# Send a GET request to the URL
response = requests.get(problemset_url)

# Get the HTML content
html_content = response.content

# Parse the HTML using BeautifulSoup
soup = BeautifulSoup(html_content, 'html.parser')

# Find the table containing the problemset
table = soup.find('table', class_='problems')

# Extract the desired columns
rows = table.find_all('tr')
problemset_data = []
header = ['#', 'Name', 'Difficulty', 'Solved']

for row in rows[1:]:
    cells = row.find_all('td')
    num = cells[0].text.strip()
    name = cells[1].text.strip()
    difficulty = cells[3].text.strip()
    solved = cells[4].text.strip()
    
    problemset_data.append([num, name, difficulty, solved])

# Create a DataFrame from the extracted data
problemset_df = pd.DataFrame(problemset_data, columns=header)

# Print the DataFrame
problemset_df

,#,Name,Difficulty,Solved
0,4A,Watermelon \n\n\nbrute forc...,800,x394103
1,71A,Way Too Long Words \n\n\nst...,800,x289869
2,231A,"Team \n\n\nbrute force,\r\n...",800,x243993
3,1A,Theatre Square \n\n\nmath,1000,x210189
4,158A,Next Round \n\n\n*special p...,800,x194010
...,...,...,...,...
95,579A,Raising Bacteria \n\n\nbitm...,1000,x46248
96,313A,Ilya and Bank Account \n\n\...,900,x46076
97,1742A,Sum \n\n\nimplementation,800,x45721
98,703A,Mishka and Game \n\n\nimple...,800,x45563
99,1692A,Marathon \n\n\nimplementation,800,x45286

### Preprocessing Problemset dataframe

###### First,
1. Split the values in the '#' column

In [163]:
# Split the values in the '#' column
problemset_df['Number'] = problemset_df['#'].str[:-1]
problemset_df['Character'] = problemset_df['#'].str[-1]

# Print the modified DataFrame
problemset_df

,#,Name,Difficulty,Solved,Number,Character
0,4A,Watermelon \n\n\nbrute forc...,800,x394103,4,A
1,71A,Way Too Long Words \n\n\nst...,800,x289869,71,A
2,231A,"Team \n\n\nbrute force,\r\n...",800,x243993,231,A
3,1A,Theatre Square \n\n\nmath,1000,x210189,1,A
4,158A,Next Round \n\n\n*special p...,800,x194010,158,A
...,...,...,...,...,...,...
95,579A,Raising Bacteria \n\n\nbitm...,1000,x46248,579,A
96,313A,Ilya and Bank Account \n\n\...,900,x46076,313,A
97,1742A,Sum \n\n\nimplementation,800,x45721,1742,A
98,703A,Mishka and Game \n\n\nimple...,800,x45563,703,A
99,1692A,Marathon \n\n\nimplementation,800,x45286,1692,A

###### Second,
2. Preprocessing Solved column

In [178]:
problemset_df['x'] = problemset_df['Solved'].str[1]
problemset_df['Solved'] = problemset_df['Solved'].str[1:]
problemset_df = problemset_df.drop(columns= ['x'])
# Print the modified DataFrame
problemset_df

,#,Name,Difficulty,Solved,Number,Character
0,4A,Watermelon \n\n\nbrute forc...,800,394103,4,A
1,71A,Way Too Long Words \n\n\nst...,800,289869,71,A
2,231A,"Team \n\n\nbrute force,\r\n...",800,243993,231,A
3,1A,Theatre Square \n\n\nmath,1000,210189,1,A
4,158A,Next Round \n\n\n*special p...,800,194010,158,A
...,...,...,...,...,...,...
95,579A,Raising Bacteria \n\n\nbitm...,1000,46248,579,A
96,313A,Ilya and Bank Account \n\n\...,900,46076,313,A
97,1742A,Sum \n\n\nimplementation,800,45721,1742,A
98,703A,Mishka and Game \n\n\nimple...,800,45563,703,A
99,1692A,Marathon \n\n\nimplementation,800,45286,1692,A

###### Third,
3. Preprocessing Name column

In [179]:
# Split the Name column when a newline character is encountered
problemset_df[['Problem Name', 'Tag']] = problemset_df['Name'].str.split('\n\n\n', expand=True)
# Drop the original Name column
problemset_df.drop('Name', axis=1, inplace=True)

# Print the modified DataFrame
problemset_df

,#,Difficulty,Solved,Number,Character,Problem Name,Tag
0,4A,800,394103,4,A,Watermelon,"brute force,\r\n math"
1,71A,800,289869,71,A,Way Too Long Words,strings
2,231A,800,243993,231,A,Team,"brute force,\r\n greedy"
3,1A,1000,210189,1,A,Theatre Square,math
4,158A,800,194010,158,A,Next Round,"*special problem,\r\n i..."
...,...,...,...,...,...,...,...
95,579A,1000,46248,579,A,Raising Bacteria,bitmasks
96,313A,900,46076,313,A,Ilya and Bank Account,"implementation,\r\n num..."
97,1742A,800,45721,1742,A,Sum,implementation
98,703A,800,45563,703,A,Mishka and Game,implementation
99,1692A,800,45286,1692,A,Marathon,implementation

###### Fourth,
4. Preprocessing Tag column
   1) Getting rid of extra characters
   2) Splitting into multiple tags columns that has either 0 or 1

In [180]:
problemset_df['Tag'] = problemset_df['Tag'].apply(lambda x: str(x).replace('\r\n', ''))


column = problemset_df['Tag']

keep_symbol = ','

for i in range(len(column)):
    symbols = [symbol for symbol in column[i] if symbol == keep_symbol or symbol.isalpha()]
    column[i] = ''.join(symbols)

problemset_df['Tag'] = column

problemset_df

,#,Difficulty,Solved,Number,Character,Problem Name,Tag
0,4A,800,394103,4,A,Watermelon,"bruteforce,math"
1,71A,800,289869,71,A,Way Too Long Words,strings
2,231A,800,243993,231,A,Team,"bruteforce,greedy"
3,1A,1000,210189,1,A,Theatre Square,math
4,158A,800,194010,158,A,Next Round,"specialproblem,implementation"
...,...,...,...,...,...,...,...
95,579A,1000,46248,579,A,Raising Bacteria,bitmasks
96,313A,900,46076,313,A,Ilya and Bank Account,"implementation,numbertheory"
97,1742A,800,45721,1742,A,Sum,implementation
98,703A,800,45563,703,A,Mishka and Game,implementation
99,1692A,800,45286,1692,A,Marathon,implementation

In [183]:
# Split the tags column into separate columns
tags_df = problemset_df['Tag'].str.get_dummies(',').add_prefix('Tag_')

# Concatenate the tags DataFrame with the original DataFrame
problemset_df = pd.concat([problemset_df, tags_df], axis=1)


# Drop duplicate columns
problemset_df = problemset_df.loc[:,~problemset_df.columns.duplicated()]

# Drop the original Name and Tage columns
problemset_df.drop(['Tag'], axis=1, inplace=True)

# Print the modified DataFrame
problemset_df

,#,Difficulty,Solved,Number,Character,Problem Name,Tag_binarysearch,Tag_bitmasks,Tag_bruteforce,Tag_constructivealgorithms,...,Tag_greedy,Tag_hashing,Tag_implementation,Tag_math,Tag_numbertheory,Tag_shortestpaths,Tag_sortings,Tag_specialproblem,Tag_strings,Tag_twopointers
0,4A,800,394103,4,A,Watermelon,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
1,71A,800,289869,71,A,Way Too Long Words,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,231A,800,243993,231,A,Team,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
3,1A,1000,210189,1,A,Theatre Square,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,158A,800,194010,158,A,Next Round,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,579A,1000,46248,579,A,Raising Bacteria,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
96,313A,900,46076,313,A,Ilya and Bank Account,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
97,1742A,800,45721,1742,A,Sum,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
98,703A,800,45563,703,A,Mishka and Game,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
99,1692A,800,45286,1692,A,Marathon,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

###### Fourth,
3. Renaming character column to Class

In [203]:
problemset_df.rename(columns={'Character': 'Class'}, inplace=True)

problemset_df.rename(columns={'#': 'Number_Class'}, inplace=True)

problemset_df

,Number_Class,Difficulty,Solved,Number,Class,Problem Name,Tag_binarysearch,Tag_bitmasks,Tag_bruteforce,Tag_constructivealgorithms,...,Tag_greedy,Tag_hashing,Tag_implementation,Tag_math,Tag_numbertheory,Tag_shortestpaths,Tag_sortings,Tag_specialproblem,Tag_strings,Tag_twopointers
0,4A,800,394103,4,A,Watermelon,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
1,71A,800,289869,71,A,Way Too Long Words,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,231A,800,243993,231,A,Team,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
3,1A,1000,210189,1,A,Theatre Square,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,158A,800,194010,158,A,Next Round,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,579A,1000,46248,579,A,Raising Bacteria,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
96,313A,900,46076,313,A,Ilya and Bank Account,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
97,1742A,800,45721,1742,A,Sum,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
98,703A,800,45563,703,A,Mishka and Game,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
99,1692A,800,45286,1692,A,Marathon,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

###### Fifth,
5. First 50 problems in problemset
#### We will keep only the submissions on the first 50 problems so that we can effectively scrape later on

In [348]:
problemset_50_df = problemset_df.head(50)
problemset_50_df['Number'] = problemset_50_df['Number'].astype(int)
problemset_50_df['Class'] = problemset_50_df['Class'].astype(str)
problemset_50_df

,Number_Class,Difficulty,Solved,Number,Class,Problem Name,Tag_binarysearch,Tag_bitmasks,Tag_bruteforce,Tag_constructivealgorithms,...,Tag_greedy,Tag_hashing,Tag_implementation,Tag_math,Tag_numbertheory,Tag_shortestpaths,Tag_sortings,Tag_specialproblem,Tag_strings,Tag_twopointers
0,4A,800,394103,4,A,Watermelon,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
1,71A,800,289869,71,A,Way Too Long Words,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,231A,800,243993,231,A,Team,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
3,1A,1000,210189,1,A,Theatre Square,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,158A,800,194010,158,A,Next Round,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
5,50A,800,189181,50,A,Domino piling,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
6,282A,800,187890,282,A,Bit++,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
7,263A,800,184964,263,A,Beautiful Matrix,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
8,112A,800,173995,112,A,Petya and Strings,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
9,339A,800,164328,339,A,Helpful Maths,0,0,0,0,...,1,0,1,0,0,0,1,0,1,0
10,281A,800,161819,281,A,Word Capitalization,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
11,236A,800,157527,236,A,Boy or Girl,0,0,1,0,...,0,0,1,0,0,0,0,0,1,0
12,118A,1000,155375,118,A,String Task,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
13,266A,800,148574,266,A,Stones on the Table,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
14,791A,800,144275,791,A,Bear and Big Brother,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
15,546A,800,136237,546,A,Soldier and Bananas,0,0,1,0,...,0,0,1,1,0,0,0,0,0,0
16,617A,800,135582,617,A,Elephant,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
17,59A,800,131871,59,A,Word,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
18,69A,1000,130609,69,A,Young Physicist,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0
19,977A,800,126541,977,A,Wrong Subtraction,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
20,96A,900,125846,96,A,Football,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
21,110A,800,116151,110,A,Nearly Lucky Number,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
22,734A,800,114111,734,A,Anton and Danik,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
23,116A,800,111520,116,A,Tram,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
24,41A,800,110782,41,A,Translation,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
25,266B,800,107949,266,B,Queue at the School,0,0,0,1,...,0,0,1,0,0,1,0,0,0,0
26,677A,800,106517,677,A,Vanya and Fence,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
27,271A,800,105419,271,A,Beautiful Year,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
28,58A,1000,104528,58,A,Chat room,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
29,122A,1000,99843,122,A,Lucky Division,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
30,1030A,800,97136,1030,A,In Search of an Easy Problem,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
31,160A,900,95472,160,A,Twins,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
32,467A,800,94655,467,A,George and Accommodation,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
33,344A,800,92373,344,A,Magnets,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
34,136A,800,92004,136,A,Presents,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
35,486A,800,89497,486,A,Calculating Function,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0
36,200B,800,88935,200,B,Drinks,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0
37,318A,900,88239,318,A,Even Odds,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
38,61A,800,86742,61,A,Ultra-Fast Mathematician,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
39,133A,900,86149,133,A,HQ9+,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
40,705A,800,84057,705,A,Hulk,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
41,228A,800,83700,228,A,Is your horseshoe on the other hoof? ...,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
42,405A,900,78667,405,A,Gravity Flip,0,0,0,0,...,1,0,1,0,0,0,1,0,0,0
43,469A,800,77003,469,A,I Wanna Be the Guy,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
44,479A,1000,75588,479,A,Expression,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
45,1328A,800,75348,1328,A,Divisibility Problem,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
46,144A,800,75127,144,A,Arrival of the General,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
47,148A,800,73903,148,A,Insomnia cure,0,0,0,1,...,0,0,1,1,0,0,0,0,0,0
48,520A,800,72918,520,A,Pangram,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
49,580A,900,72911,580,A,Kefa and First Steps,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0

In [349]:
problemset_df.to_csv("Processed_problemset_df.csv", index = False)

### friends problemset

#### Scraping friends who solved the problems in the problemset of the first page in codeforces

In [35]:
base_url = 'https://codeforces.com/problemset/status/'

# 'https://codeforces.com/problemset/status/228/problem/A/page/'

header = ['#', 'When', 'Who', 'Problem', 'Language', 'Verdict', 'Time', 'Memory']   
friends_problemset_df = pd.DataFrame(columns=header)


# Iterate over the values in 'Number' and 'Character' columns
for num, char in zip(problemset_df['Number'], problemset_df['Class']):
    
    # Access the protected page
    page = 1
    problem_url = f"{base_url}{num}/problem/{char}/page/"
    problem_page_url = f"{problem_url}{page}?friends=on"
    response = session.get(problem_page_url)
    soup = BeautifulSoup(response.content, 'lxml')
    s = soup.find('div', id= 'body')
    
    # Extract the total number of pages
    pagination_div = s.find('div', style='margin-top:1em;' ).find('div',class_= 'pagination')
    if pagination_div is not None:
        pages = pagination_div.find_all('a')
        total_pages = int(pages[-2].text.strip())
    else:
        total_pages = 1
        
    # Extract the desired columns
    data = []
    
    print(total_pages)
    # Iterate over the pages
    for page in range(1, total_pages + 1):
        problem_page_url = f"{problem_url}{page}?friends=on"
        print(problem_page_url)

        # Send a GET request to the URL
        response = session.get(problem_page_url)
        
        soup = BeautifulSoup(response.content, 'html.parser')

        table = soup.find('table', {'class': 'status-frame-datatable'})
        rows = table.find_all('tr')

        for row in rows[1:]:
            cells = row.find_all('td')
            if len(cells) >= 8:
                num = cells[0].text.strip()
                when = cells[1].text.strip()
                who = cells[2].text.strip()
                problem = cells[3].text.strip()
                lang = cells[4].text.strip()
                verdict = cells[5].text.strip()
                time = cells[6].text.strip()
                memory = cells[7].text.strip()

                data.append([num, when, who, problem, lang, verdict, time, memory])

    # Create a DataFrame from the extracted data
    friends_problem_df = pd.DataFrame(data, columns=header)
    friends_problemset_df = pd.concat([friends_problemset_df,friends_problem_df], axis=0)

3
https://codeforces.com/problemset/status/4/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/4/problem/A/page/2?friends=on
https://codeforces.com/problemset/status/4/problem/A/page/3?friends=on
3
https://codeforces.com/problemset/status/71/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/71/problem/A/page/2?friends=on
https://codeforces.com/problemset/status/71/problem/A/page/3?friends=on
3
https://codeforces.com/problemset/status/231/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/231/problem/A/page/2?friends=on
https://codeforces.com/problemset/status/231/problem/A/page/3?friends=on
2
https://codeforces.com/problemset/status/1/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/1/problem/A/page/2?friends=on
3
https://codeforces.com/problemset/status/158/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/158/problem/A/page/2?friends=on
https://codeforces.com/problemset/status/158/problem/A/page/3?friends=on
2
https://codeforces.com/problemset/status/50/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/50/problem/A/page/2?friends=on
3
https://codeforces.com/problemset/status/282/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/282/problem/A/page/2?friends=on
https://codeforces.com/problemset/status/282/problem/A/page/3?friends=on
3
https://codeforces.com/problemset/status/263/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/263/problem/A/page/2?friends=on
https://codeforces.com/problemset/status/263/problem/A/page/3?friends=on
3
https://codeforces.com/problemset/status/112/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/112/problem/A/page/2?friends=on
https://codeforces.com/problemset/status/112/problem/A/page/3?friends=on
3
https://codeforces.com/problemset/status/339/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/339/problem/A/page/2?friends=on
https://codeforces.com/problemset/status/339/problem/A/page/3?friends=on
2
https://codeforces.com/problemset/status/281/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/281/problem/A/page/2?friends=on
3
https://codeforces.com/problemset/status/236/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/236/problem/A/page/2?friends=on
https://codeforces.com/problemset/status/236/problem/A/page/3?friends=on
2
https://codeforces.com/problemset/status/118/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/118/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/266/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/266/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/791/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/791/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/546/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/546/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/617/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/617/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/59/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/59/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/69/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/69/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/977/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/977/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/96/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/96/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/110/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/110/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/734/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/734/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/116/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/116/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/41/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/41/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/266/problem/B/page/1?friends=on
https://codeforces.com/problemset/status/266/problem/B/page/2?friends=on
2
https://codeforces.com/problemset/status/677/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/677/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/271/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/271/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/58/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/58/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/122/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/122/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/1030/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/1030/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/160/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/160/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/467/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/467/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/344/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/344/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/136/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/136/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/486/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/486/problem/A/page/2?friends=on

KeyboardInterrupt:

# test

In [360]:
base_url = 'https://codeforces.com/problemset/status/'

# 'https://codeforces.com/problemset/status/228/problem/A/page/'

header = ['#', 'When', 'Who', 'Problem', 'Language', 'Verdict', 'Time', 'Memory']   
rama = pd.DataFrame(columns=header)


# Iterate over the values in 'Number' and 'Character' columns
for num, char in zip(problemset_df['Number'], problemset_df['Class']):
    
    # Access the protected page
    page = 1
    problem_url = f"{base_url}{num}/problem/{char}/page/"
    problem_page_url = f"{problem_url}{page}?friends=on"
    response = session.get(problem_page_url)
    soup = BeautifulSoup(response.content, 'lxml')
    s = soup.find('div', id= 'body')
    
    # Extract the total number of pages
    pagination_div = s.find('div', style='margin-top:1em;' ).find('div',class_= 'pagination')
    if pagination_div is not None:
        pages = pagination_div.find_all('a')
        total_pages = int(pages[-2].text.strip())
    else:
        total_pages = 1
        
    # Extract the desired columns
    data = []
    
    print(total_pages)
    # Iterate over the pages
    for page in range(1, total_pages + 1):
        problem_page_url = f"{problem_url}{page}?friends=on"
        print(problem_page_url)

        # Send a GET request to the URL
        response = session.get(problem_page_url)
        
        soup = BeautifulSoup(response.content, 'html.parser')

        table = soup.find('table', {'class': 'status-frame-datatable'})
        rows = table.find_all('tr')

        for row in rows[1:]:
            cells = row.find_all('td')
            if len(cells) >= 8:
                num = cells[0].text.strip()
                when = cells[1].text.strip()
                who = cells[2].text.strip()
                problem = cells[3].text.strip()
                lang = cells[4].text.strip()
                verdict = cells[5].text.strip()
                time = cells[6].text.strip()
                memory = cells[7].text.strip()

                data.append([num, when, who, problem, lang, verdict, time, memory])

    # Create a DataFrame from the extracted data
    friends_problem_df = pd.DataFrame(data, columns=header)
    rama = pd.concat([rama,friends_problem_df], axis=0)

3
https://codeforces.com/problemset/status/4/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/4/problem/A/page/2?friends=on
https://codeforces.com/problemset/status/4/problem/A/page/3?friends=on
3
https://codeforces.com/problemset/status/71/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/71/problem/A/page/2?friends=on
https://codeforces.com/problemset/status/71/problem/A/page/3?friends=on
3
https://codeforces.com/problemset/status/231/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/231/problem/A/page/2?friends=on
https://codeforces.com/problemset/status/231/problem/A/page/3?friends=on
2
https://codeforces.com/problemset/status/1/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/1/problem/A/page/2?friends=on
3
https://codeforces.com/problemset/status/158/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/158/problem/A/page/2?friends=on
https://codeforces.com/problemset/status/158/problem/A/page/3?friends=on
2
https://codeforces.com/problemset/status/50/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/50/problem/A/page/2?friends=on
3
https://codeforces.com/problemset/status/282/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/282/problem/A/page/2?friends=on
https://codeforces.com/problemset/status/282/problem/A/page/3?friends=on
3
https://codeforces.com/problemset/status/263/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/263/problem/A/page/2?friends=on
https://codeforces.com/problemset/status/263/problem/A/page/3?friends=on
3
https://codeforces.com/problemset/status/112/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/112/problem/A/page/2?friends=on
https://codeforces.com/problemset/status/112/problem/A/page/3?friends=on
3
https://codeforces.com/problemset/status/339/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/339/problem/A/page/2?friends=on
https://codeforces.com/problemset/status/339/problem/A/page/3?friends=on
2
https://codeforces.com/problemset/status/281/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/281/problem/A/page/2?friends=on
3
https://codeforces.com/problemset/status/236/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/236/problem/A/page/2?friends=on
https://codeforces.com/problemset/status/236/problem/A/page/3?friends=on
2
https://codeforces.com/problemset/status/118/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/118/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/266/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/266/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/791/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/791/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/546/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/546/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/617/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/617/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/59/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/59/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/69/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/69/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/977/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/977/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/96/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/96/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/110/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/110/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/734/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/734/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/116/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/116/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/41/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/41/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/266/problem/B/page/1?friends=on
https://codeforces.com/problemset/status/266/problem/B/page/2?friends=on
2
https://codeforces.com/problemset/status/677/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/677/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/271/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/271/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/58/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/58/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/122/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/122/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/1030/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/1030/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/160/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/160/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/467/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/467/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/344/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/344/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/136/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/136/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/486/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/486/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/200/problem/B/page/1?friends=on
https://codeforces.com/problemset/status/200/problem/B/page/2?friends=on
2
https://codeforces.com/problemset/status/318/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/318/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/61/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/61/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/133/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/133/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/705/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/705/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/228/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/228/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/405/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/405/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/469/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/469/problem/A/page/2?friends=on
1
https://codeforces.com/problemset/status/479/problem/A/page/1?friends=on
2
https://codeforces.com/problemset/status/1328/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/1328/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/144/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/144/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/148/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/148/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/520/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/520/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/580/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/580/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/158/problem/B/page/1?friends=on
https://codeforces.com/problemset/status/158/problem/B/page/2?friends=on
2
https://codeforces.com/problemset/status/208/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/208/problem/A/page/2?friends=on

2
https://codeforces.com/problemset/status/443/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/443/problem/A/page/2?friends=on
1
https://codeforces.com/problemset/status/131/problem/A/page/1?friends=on
2
https://codeforces.com/problemset/status/996/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/996/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/25/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/25/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/268/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/268/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/785/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/785/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/337/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/337/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/141/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/141/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/1335/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/1335/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/4/problem/C/page/1?friends=on
https://codeforces.com/problemset/status/4/problem/C/page/2?friends=on
2
https://codeforces.com/problemset/status/510/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/510/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/230/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/230/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/492/problem/B/page/1?friends=on
https://codeforces.com/problemset/status/492/problem/B/page/2?friends=on
2
https://codeforces.com/problemset/status/427/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/427/problem/A/page/2?friends=on
1
https://codeforces.com/problemset/status/155/problem/A/page/1?friends=on
3
https://codeforces.com/problemset/status/230/problem/B/page/1?friends=on
https://codeforces.com/problemset/status/230/problem/B/page/2?friends=on
https://codeforces.com/problemset/status/230/problem/B/page/3?friends=on
2
https://codeforces.com/problemset/status/750/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/750/problem/A/page/2?friends=on
1
https://codeforces.com/problemset/status/339/problem/B/page/1?friends=on
2
https://codeforces.com/problemset/status/1352/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/1352/problem/A/page/2?friends=on
1
https://codeforces.com/problemset/status/581/problem/A/page/1?friends=on
1
https://codeforces.com/problemset/status/723/problem/A/page/1?friends=on
2
https://codeforces.com/problemset/status/732/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/732/problem/A/page/2?friends=on
1
https://codeforces.com/problemset/status/451/problem/A/page/1?friends=on
1
https://codeforces.com/problemset/status/1154/problem/A/page/1?friends=on
1
https://codeforces.com/problemset/status/1399/problem/A/page/1?friends=on
1
https://codeforces.com/problemset/status/1409/problem/A/page/1?friends=on
2
https://codeforces.com/problemset/status/189/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/189/problem/A/page/2?friends=on
1
https://codeforces.com/problemset/status/151/problem/A/page/1?friends=on
1
https://codeforces.com/problemset/status/466/problem/A/page/1?friends=on
1
https://codeforces.com/problemset/status/472/problem/A/page/1?friends=on
1
https://codeforces.com/problemset/status/432/problem/A/page/1?friends=on
2
https://codeforces.com/problemset/status/1512/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/1512/problem/A/page/2?friends=on
1
https://codeforces.com/problemset/status/1367/problem/A/page/1?friends=on
1
https://codeforces.com/problemset/status/758/problem/A/page/1?friends=on
2
https://codeforces.com/problemset/status/381/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/381/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/490/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/490/problem/A/page/2?friends=on
1
https://codeforces.com/problemset/status/1343/problem/B/page/1?friends=on
2
https://codeforces.com/problemset/status/630/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/630/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/455/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/455/problem/A/page/2?friends=on
1
https://codeforces.com/problemset/status/32/problem/B/page/1?friends=on
2
https://codeforces.com/problemset/status/706/problem/B/page/1?friends=on
https://codeforces.com/problemset/status/706/problem/B/page/2?friends=on
1
https://codeforces.com/problemset/status/1560/problem/A/page/1?friends=on
2
https://codeforces.com/problemset/status/1703/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/1703/problem/A/page/2?friends=on
2
https://codeforces.com/problemset/status/579/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/579/problem/A/page/2?friends=on
1
https://codeforces.com/problemset/status/313/problem/A/page/1?friends=on
2
https://codeforces.com/problemset/status/1742/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/1742/problem/A/page/2?friends=on
1
https://codeforces.com/problemset/status/703/problem/A/page/1?friends=on
2
https://codeforces.com/problemset/status/1692/problem/A/page/1?friends=on
https://codeforces.com/problemset/status/1692/problem/A/page/2?friends=on

In [361]:
rama

,#,When,Who,Problem,Language,Verdict,Time,Memory
0,176398672,Oct/15/2022 23:16,HASSAN_GH,4A - Watermelon,Python 3,Accepted,92Â ms,0Â KB
1,127833250,Sep/04/2021 13:39,MuhammadMak,4A - Watermelon,PHP,Accepted,92Â ms,5900Â KB
2,177056900,Oct/19/2022 23:08,obada_katma,4A - Watermelon,Python 3,Accepted,92Â ms,0Â KB
3,88731590,Aug/02/2020 15:43,Baraa_Armoush,4A - Watermelon,Python 3,Accepted,186Â ms,6500Â KB
4,88731633,Aug/02/2020 15:43,Baraa_Armoush,4A - Watermelon,PyPy 3,Accepted,280Â ms,19700Â KB
...,...,...,...,...,...,...,...,...
48,160525370,Jun/14/2022 17:37,DARK-N,1692A - Marathon,GNU C++20 (64),Accepted,15Â ms,0Â KB
49,160522552,Jun/14/2022 17:36,_SADIEM_,1692A - Marathon,GNU C++20 (64),Accepted,15Â ms,0Â KB
50,160546538,Jun/14/2022 17:46,Diab,1692A - Marathon,GNU C++17,Accepted,15Â ms,0Â KB
51,201770743,Apr/12/2023 05:18,obada_katma#,1692A - Marathon,GNU C++20 (64),Accepted,15Â ms,100Â KB
52,194129211,Feb/18/2023 17:48,Mohammed_Abdelkareem,1692A - Marathon,GNU C++17,Accepted,15Â ms,0Â KB

### Preprocessing friends problemset

###### First,
1. Preprocessing Problem column
   1) Splitting Problem column to Number_Class column and Problem_name column
   2) Splitting Number_Class column to Number column and Class column

In [287]:
friends_problemset_df[['Number_Class','Problem_name']] = friends_problemset_df['Problem'].str.split(' - ', expand=True)

# Split the values in the 'Number_character' column
friends_problemset_df['Number'] = friends_problemset_df['Number_Class'].str[:-1]
friends_problemset_df['Class'] = friends_problemset_df['Number_Class'].str[-1]


friends_problemset_df = friends_problemset_df.drop(columns = ['Problem'])
friends_problemset_df

,#,When,Who,Language,Verdict,Time,Memory,Problem_name,Number,Class,Number_Class
0,176398672,Oct/15/2022 23:16,HASSAN_GH,Python 3,Accepted,92Â ms,0Â KB,Watermelon,4,A,4A
1,127833250,Sep/04/2021 13:39,MuhammadMak,PHP,Accepted,92Â ms,5900Â KB,Watermelon,4,A,4A
2,177056900,Oct/19/2022 23:08,obada_katma,Python 3,Accepted,92Â ms,0Â KB,Watermelon,4,A,4A
3,88731590,Aug/02/2020 15:43,Baraa_Armoush,Python 3,Accepted,186Â ms,6500Â KB,Watermelon,4,A,4A
4,88731633,Aug/02/2020 15:43,Baraa_Armoush,PyPy 3,Accepted,280Â ms,19700Â KB,Watermelon,4,A,4A
...,...,...,...,...,...,...,...,...,...,...,...
6869,160525370,Jun/14/2022 17:37,DARK-N,GNU C++20 (64),Accepted,15Â ms,0Â KB,Marathon,1692,A,1692A
6870,160522552,Jun/14/2022 17:36,_SADIEM_,GNU C++20 (64),Accepted,15Â ms,0Â KB,Marathon,1692,A,1692A
6871,160546538,Jun/14/2022 17:46,Diab,GNU C++17,Accepted,15Â ms,0Â KB,Marathon,1692,A,1692A
6872,201770743,Apr/12/2023 05:18,obada_katma#,GNU C++20 (64),Accepted,15Â ms,100Â KB,Marathon,1692,A,1692A
6873,194129211,Feb/18/2023 17:48,Mohammed_Abdelkareem,GNU C++17,Accepted,15Â ms,0Â KB,Marathon,1692,A,1692A

In [350]:
friends_problemset_df.to_csv('friends_problemset_df_without_source_code.csv', index=False, encoding = 'utf-8')
# friends_problemset_df = pd.read_csv('friends_problemset_df_without_source_code.csv')

##### Second
2. Preprocessing Who column
###### I have only 121 friends but here the unique values of my friends is more than 121

In [288]:
print(friends_problemset_df['Who'].unique(),len(friends_problemset_df['Who'].unique()))

['HASSAN_GH' 'MuhammadMak' 'obada_katma' 'Baraa_Armoush' '7nooOoOoon'
 'Kavaliro' 'AhmadShahal' 'kinannotfound' 'obadaa.masri' 'ShathaS2003'
 'samer_orfali#' 'Mohammad_Kartoumeh' 'yaser.harba' 'samer_orfali'
 '_SADIEM_' 'Karam_mohmd' 'amarashujaa' '099450735z' 'IT-24-' '7amzahsa'
 'Abd_HM' '_OmarAbdo' 'Alaa-Kaadan' 'masa_beydoun' 'codeiologist'
 'Grapeee' '3bdo_Farah' 'Bicso' 'mohammed_kurdi' 'RetiringNextCentury'
 'M.Qattan' 'Bassam1412' 'Alaa_em_123' 'Nour-Aldeen' '_s_h_a_m__'
 'abbas.az408' 'AbodeKu' 'Mohammed--alhefawe' 'Wiaam_SA' 'sarah.m.akkad'
 'Ansam092' 'Conan_y65' 'Waellhasan' 'ali.alnahhas.22' 'sidratello9'
 'Diab' 'ghaith.clash88' 'NawarAlTibi' 'Brre.Hemo' 'Qddo' 'anas_allaham'
 'sanji333333' 'Kareembo' 'A.mohamad' 'Abdulrhaim_Ma' 'Tashleef'
 'RamaRehawi' 'abdalrhman.alkafry' 'Zaid_Al_Habbal' 'ghina.alrefai'
 'MarioAndrawos' 'sepsa.m' 'SaeedSabbagh' 'Sarah_nn' 'Bsher' 'Hamza_99'
 'Ahmed-yaser' 'OmranMk' 'AbdAR' 'a7mad_taieb' 'Zeina_Albarre'
 'Anti_tourist4000' '_Salty' 'The_soviet_cat' 'Zaher' 'ZENGOO'
 'Mounir_Maleh' 'abod3e9' 'Raed_Sb' 'Lanakhaled' 'Amr_Kart' 'DARK-N'
 'A.M.B.E' 'AbdAlrhman_QaraBolad' 'Abd_Alrahman_Alsyed' 'Hamza_Alattar.1'
 'Raneem.Alhassan' 'mlakdyab578' 'Mohamed-Omran' 'MuhannadW'
 'Mohammed_Abdelkareem' 'RedNextCentury' 'abd-alrzaq' 'KHALED.TELLO'
 'Dodeh' '_Mockingjay_' 'AmmarDab3an' '0xOm4r' 'Alhomse'
 '043_33798_Nuraiym-7' '0xessam' 'Yaman_Alwaza' 'Mohammad_Alassali'
 'ahmad_alghadban' 'abdalkader-s' 'Mohammed_Abdelkareem#' 'mkdad_taleb'
 'Omani' 'MouayadL7' 'Ahmad7_7' 'dee..' 'MouazBudier' '8_8_2003_aliqasm'
 'Alaatnt' 'Grapeee#' 'Lanakhaled#' 'Fadi_Futainah' 'Mohamed-Omran#'
 'Waellhasan#' 'ShadyH6' '-_Thunder_-' 'RedNextCentury#' 'Ghinanana'
 'Baraa_Armoush#' 'Diab#' '* Mohammad_Kartoumeh' '657311511710811697110'
 'RetiringNextCentury#' '* RedNextCentury' '_SoN_' 'Bsher#'
 'SaeedSabbagh#' 'Qddo#' '* Baraa_Armoush' 'AhmadShahal#' '* SaeedSabbagh'
 'Mohammad_Kartoumeh#' 'sepsa.m#' 'ahmad_alghadban#' '_SADIEM_#'
 '* Kavaliro' 'Dr-Code' '* abdalkader-s' 'Kavaliro#' 'Zaher#' '* Bsher'
 'Amr_Kart#' '* samer_orfali' '_OmarAbdo#' '* Grapeee' '* yaser.harba'
 '* Yaman_Alwaza' 'abdalkader-s#' '* Zaher' 'yaser.harba#' 'MouazBudier#'
 'Fadi_Futainah#' '* Ahmad7_7' 'Raneem.Alhassan#' '3bdo_Farah#'
 'just for fun: Bsher, Baraa_Armoush#' 'AmmarDab3an#'
 'NH: RENGOO, ZENGOO#' 'anas_allaham#' 'Zeina_Albarre#' 'ghina.alrefai#'
 '0xessam#' 'kinannotfound#' 'obada_katma#'] 169

In [289]:
# Replace rows with '#' at the end of 'Who' values with the value without '#'
friends_problemset_df['Who'] = friends_problemset_df['Who'].apply(lambda x: str(x).replace('#', ''))
# friends_problemset_df = friends_problemset_df[~friends_problemset_df['Who'].str.endswith('#')]

# Replace rows with '* ' at the beginning of 'Who' values with the value without '* '
friends_problemset_df['Who'] = friends_problemset_df['Who'].apply(lambda x: str(x).replace('* ', ''))
# friends_problemset_df = friends_problemset_df[~friends_problemset_df['Who'].str.startswith('*')]

print(friends_problemset_df['Who'].unique(), len(friends_problemset_df['Who'].unique()))

['HASSAN_GH' 'MuhammadMak' 'obada_katma' 'Baraa_Armoush' '7nooOoOoon'
 'Kavaliro' 'AhmadShahal' 'kinannotfound' 'obadaa.masri' 'ShathaS2003'
 'samer_orfali' 'Mohammad_Kartoumeh' 'yaser.harba' '_SADIEM_'
 'Karam_mohmd' 'amarashujaa' '099450735z' 'IT-24-' '7amzahsa' 'Abd_HM'
 '_OmarAbdo' 'Alaa-Kaadan' 'masa_beydoun' 'codeiologist' 'Grapeee'
 '3bdo_Farah' 'Bicso' 'mohammed_kurdi' 'RetiringNextCentury' 'M.Qattan'
 'Bassam1412' 'Alaa_em_123' 'Nour-Aldeen' '_s_h_a_m__' 'abbas.az408'
 'AbodeKu' 'Mohammed--alhefawe' 'Wiaam_SA' 'sarah.m.akkad' 'Ansam092'
 'Conan_y65' 'Waellhasan' 'ali.alnahhas.22' 'sidratello9' 'Diab'
 'ghaith.clash88' 'NawarAlTibi' 'Brre.Hemo' 'Qddo' 'anas_allaham'
 'sanji333333' 'Kareembo' 'A.mohamad' 'Abdulrhaim_Ma' 'Tashleef'
 'RamaRehawi' 'abdalrhman.alkafry' 'Zaid_Al_Habbal' 'ghina.alrefai'
 'MarioAndrawos' 'sepsa.m' 'SaeedSabbagh' 'Sarah_nn' 'Bsher' 'Hamza_99'
 'Ahmed-yaser' 'OmranMk' 'AbdAR' 'a7mad_taieb' 'Zeina_Albarre'
 'Anti_tourist4000' '_Salty' 'The_soviet_cat' 'Zaher' 'ZENGOO'
 'Mounir_Maleh' 'abod3e9' 'Raed_Sb' 'Lanakhaled' 'Amr_Kart' 'DARK-N'
 'A.M.B.E' 'AbdAlrhman_QaraBolad' 'Abd_Alrahman_Alsyed' 'Hamza_Alattar.1'
 'Raneem.Alhassan' 'mlakdyab578' 'Mohamed-Omran' 'MuhannadW'
 'Mohammed_Abdelkareem' 'RedNextCentury' 'abd-alrzaq' 'KHALED.TELLO'
 'Dodeh' '_Mockingjay_' 'AmmarDab3an' '0xOm4r' 'Alhomse'
 '043_33798_Nuraiym-7' '0xessam' 'Yaman_Alwaza' 'Mohammad_Alassali'
 'ahmad_alghadban' 'abdalkader-s' 'mkdad_taleb' 'Omani' 'MouayadL7'
 'Ahmad7_7' 'dee..' 'MouazBudier' '8_8_2003_aliqasm' 'Alaatnt'
 'Fadi_Futainah' 'ShadyH6' '-_Thunder_-' 'Ghinanana'
 '657311511710811697110' '_SoN_' 'Dr-Code'
 'just for fun: Bsher, Baraa_Armoush' 'NH: RENGOO, ZENGOO'] 121

In [290]:
friends_problemset_df

,#,When,Who,Language,Verdict,Time,Memory,Problem_name,Number,Class,Number_Class
0,176398672,Oct/15/2022 23:16,HASSAN_GH,Python 3,Accepted,92Â ms,0Â KB,Watermelon,4,A,4A
1,127833250,Sep/04/2021 13:39,MuhammadMak,PHP,Accepted,92Â ms,5900Â KB,Watermelon,4,A,4A
2,177056900,Oct/19/2022 23:08,obada_katma,Python 3,Accepted,92Â ms,0Â KB,Watermelon,4,A,4A
3,88731590,Aug/02/2020 15:43,Baraa_Armoush,Python 3,Accepted,186Â ms,6500Â KB,Watermelon,4,A,4A
4,88731633,Aug/02/2020 15:43,Baraa_Armoush,PyPy 3,Accepted,280Â ms,19700Â KB,Watermelon,4,A,4A
...,...,...,...,...,...,...,...,...,...,...,...
6869,160525370,Jun/14/2022 17:37,DARK-N,GNU C++20 (64),Accepted,15Â ms,0Â KB,Marathon,1692,A,1692A
6870,160522552,Jun/14/2022 17:36,_SADIEM_,GNU C++20 (64),Accepted,15Â ms,0Â KB,Marathon,1692,A,1692A
6871,160546538,Jun/14/2022 17:46,Diab,GNU C++17,Accepted,15Â ms,0Â KB,Marathon,1692,A,1692A
6872,201770743,Apr/12/2023 05:18,obada_katma,GNU C++20 (64),Accepted,15Â ms,100Â KB,Marathon,1692,A,1692A
6873,194129211,Feb/18/2023 17:48,Mohammed_Abdelkareem,GNU C++17,Accepted,15Â ms,0Â KB,Marathon,1692,A,1692A

##### Third, 
3. Preprocessing data to keep only the C++ and Accepted submissions

In [291]:
# Keep only rows with "Accepted" verdict
friends_problemset_df = friends_problemset_df[friends_problemset_df['Verdict'].str.contains("Accepted", regex=False)]

friends_problemset_df = friends_problemset_df.drop(columns = ['Verdict'])

# Keep only rows with "C++" language
friends_problemset_df = friends_problemset_df[friends_problemset_df['Language'].str.contains("C++", regex=False)]

friends_problemset_df

,#,When,Who,Language,Time,Memory,Problem_name,Number,Class,Number_Class
8,164909440,Jul/19/2022 17:36,kinannotfound,GNU C++17,30Â ms,0Â KB,Watermelon,4,A,4A
9,168664652,Aug/17/2022 10:44,kinannotfound,GNU C++20 (64),30Â ms,0Â KB,Watermelon,4,A,4A
10,147200215,Feb/21/2022 20:13,obadaa.masri,GNU C++14,30Â ms,0Â KB,Watermelon,4,A,4A
12,172236866,Sep/15/2022 14:51,ShathaS2003,GNU C++17,30Â ms,0Â KB,Watermelon,4,A,4A
13,37352281,Apr/15/2018 14:50,samer_orfali,GNU C++,30Â ms,3200Â KB,Watermelon,4,A,4A
...,...,...,...,...,...,...,...,...,...,...
6869,160525370,Jun/14/2022 17:37,DARK-N,GNU C++20 (64),15Â ms,0Â KB,Marathon,1692,A,1692A
6870,160522552,Jun/14/2022 17:36,_SADIEM_,GNU C++20 (64),15Â ms,0Â KB,Marathon,1692,A,1692A
6871,160546538,Jun/14/2022 17:46,Diab,GNU C++17,15Â ms,0Â KB,Marathon,1692,A,1692A
6872,201770743,Apr/12/2023 05:18,obada_katma,GNU C++20 (64),15Â ms,100Â KB,Marathon,1692,A,1692A
6873,194129211,Feb/18/2023 17:48,Mohammed_Abdelkareem,GNU C++17,15Â ms,0Â KB,Marathon,1692,A,1692A

In [261]:
friends_problemset_df.to_csv('Preprocessed_friends_problemset_df_without_source_code.csv', index=False)

###### Third,
3. Friends submission on first 50 problems in problemset

In [323]:
friends_problemset_df['Number'] = friends_problemset_df['Number'].astype(int)
friends_problemset_df['Class'] = friends_problemset_df['Class'].astype(str)

friends_problemset_50_df = friends_problemset_df.merge(problemset_50_df, on = ['Number', 'Class', 'Number_Class'])

friends_problemset_50_df

,#,When,Who,Language,Time,Memory,Problem_name,Number,Class,Number_Class,...,Tag_greedy,Tag_hashing,Tag_implementation,Tag_math,Tag_numbertheory,Tag_shortestpaths,Tag_sortings,Tag_specialproblem,Tag_strings,Tag_twopointers
0,164909440,Jul/19/2022 17:36,kinannotfound,GNU C++17,30Â ms,0Â KB,Watermelon,4,A,4A,...,0,0,0,1,0,0,0,0,0,0
1,168664652,Aug/17/2022 10:44,kinannotfound,GNU C++20 (64),30Â ms,0Â KB,Watermelon,4,A,4A,...,0,0,0,1,0,0,0,0,0,0
2,147200215,Feb/21/2022 20:13,obadaa.masri,GNU C++14,30Â ms,0Â KB,Watermelon,4,A,4A,...,0,0,0,1,0,0,0,0,0,0
3,172236866,Sep/15/2022 14:51,ShathaS2003,GNU C++17,30Â ms,0Â KB,Watermelon,4,A,4A,...,0,0,0,1,0,0,0,0,0,0
4,37352281,Apr/15/2018 14:50,samer_orfali,GNU C++,30Â ms,3200Â KB,Watermelon,4,A,4A,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3874,172442471,Sep/17/2022 13:21,ghina.alrefai,GNU C++20 (64),15Â ms,0Â KB,Pangram,520,A,520A,...,0,0,1,0,0,0,0,0,1,0
3875,195379716,Feb/28/2023 23:20,Wiaam_SA,GNU C++17,15Â ms,100Â KB,Pangram,520,A,520A,...,0,0,1,0,0,0,0,0,1,0
3876,181336513,Nov/17/2022 19:35,AbodeKu,GNU C++17,15Â ms,0Â KB,Pangram,520,A,520A,...,0,0,1,0,0,0,0,0,1,0
3877,68767582,Jan/14/2020 13:32,Brre.Hemo,GNU C++17,31Â ms,0Â KB,Pangram,520,A,520A,...,0,0,1,0,0,0,0,0,1,0
3878,109362084,Mar/08/2021 00:04,Brre.Hemo,GNU C++17,31Â ms,200Â KB,Pangram,520,A,520A,...,0,0,1,0,0,0,0,0,1,0

In [265]:
friends_problemset_50_df.to_csv('Preprocessed_friends_problemset_50_df_without_source_code.csv', index=False)

In [293]:
# Split the DataFrame into four equal-sized DataFrames
split_data = np.array_split(friends_problemset_50_df, 4)

# Access the individual DataFrames
friends_problemset_50_df1, friends_problemset_50_df2, friends_problemset_50_df3, friends_problemset_50_df4 = split_data[0], split_data[1], split_data[2], split_data[3]

# Check the sizes of the DataFrames
print(len(friends_problemset_50_df1)) 
print(len(friends_problemset_50_df2)) 
print(len(friends_problemset_50_df3))  
print(len(friends_problemset_50_df4))

970
970
970
969

### Problem submissions source code dataset

##### We will now scrape the source code for each of the friends_problemset_50_df1,  riends_problemset_50_df2, friends_problemset_50_df3, friends_problemset_50_df4 but on different laptops (so that we can get more requests)

In [120]:
if os.path.exists('failed_submission.csv'):
    failed_submission = pd.read_csv("failed_submission.csv")
    
    # Find the index where starting_point['#'] is equal to the specific value
    start_index = friends_problemset_50_df1[friends_problemset_50_df1['#'] == failed_submission['#'][0]].index[0]
    
    # Slice the DataFrame to include rows starting from the identified index
    starting_point = friends_problemset_50_df1.loc[start_index:]
    os.remove('failed_submission.csv')

else:
    start_index = friends_problemset_50_df1[friends_problemset_50_df1['#'] == 11935165].index[0]
    
    # Slice the DataFrame to include rows starting from the identified index
    starting_point = friends_problemset_50_df1.loc[start_index:]
#     starting_point = friends_problemset_50_df1
    

# Iterate over the values in 'Number' and '#' columns
for num, submission in zip(starting_point['Number'], starting_point['#']):
        # The base URL for the submission page
        submission_url = f'https://codeforces.com/contest/{num}/submission/{submission}'
        print(submission_url)

        # Send a GET request to the URL
        response = requests.get(submission_url)

        # Check if the request was successful
        if response.status_code == 200:
            # Parse the HTML content using BeautifulSoup
            soup = BeautifulSoup(response.content, 'html.parser')

            # Find the element containing the source code
            source_elem = soup.select('#program-source-text')

            # Check if the element was found
            if source_elem:
                # Convert the HTML source code to plain text
                source = html.unescape(source_elem[0].decode_contents())

                # Path to the successful_submission file
                successful_submissions = "successful_submissions.csv"

                # Open the file in append mode and write the data
                with open(successful_submissions, "a", newline="", encoding='utf-8') as file:
                    writer = csv.DictWriter(file, fieldnames=["#", "Number", 'Source_code'])

                    # Write the header row if the file is empty
                    if file.tell() == 0:
                        writer.writeheader()

                    # Append the data rows
                    writer.writerows([{"#": submission, "Number": num, "Source_code":source}])
            else:
                print(f'Failed to find source code for submission {submission} in contest {num}')
                                                
                # Path to the failed_submission.csv file
                failed_submission = "failed_submission.csv"

                # Open the file in append mode and write the data
                with open(failed_submission, "w", newline="", encoding='utf-8') as file:
                    writer = csv.DictWriter(file, fieldnames=["#", "Number"])

                    # Write the header row if the file is empty
                    if file.tell() == 0:
                        writer.writeheader()

                    # Append the data rows
                    writer.writerows([{"#": submission, "Number": num}])
                    
                winsound.PlaySound('frog.wav', winsound.SND_FILENAME)
                break
                
        else:
            print(f'Failed to retrieve submission {submission} in contest {num}')
        time.sleep(5)

https://codeforces.com/contest/339/submission/196939273
https://codeforces.com/contest/339/submission/170392948
https://codeforces.com/contest/339/submission/202082934
https://codeforces.com/contest/339/submission/71821352
https://codeforces.com/contest/339/submission/158241038
https://codeforces.com/contest/339/submission/175678154
https://codeforces.com/contest/339/submission/58838519
https://codeforces.com/contest/339/submission/192504043
https://codeforces.com/contest/339/submission/166609153
https://codeforces.com/contest/339/submission/169744556
https://codeforces.com/contest/339/submission/160079851
https://codeforces.com/contest/339/submission/161365443
https://codeforces.com/contest/339/submission/159533920
https://codeforces.com/contest/339/submission/79610758
https://codeforces.com/contest/339/submission/196006462
https://codeforces.com/contest/339/submission/101964930
https://codeforces.com/contest/339/submission/71916954
https://codeforces.com/contest/339/submission/109219876
https://codeforces.com/contest/339/submission/193521090
https://codeforces.com/contest/339/submission/164181950
https://codeforces.com/contest/339/submission/180281294
https://codeforces.com/contest/339/submission/125018859
https://codeforces.com/contest/339/submission/193556464
https://codeforces.com/contest/339/submission/152849028
https://codeforces.com/contest/339/submission/125883148
https://codeforces.com/contest/339/submission/123971907
https://codeforces.com/contest/339/submission/34576494
https://codeforces.com/contest/339/submission/156889938
https://codeforces.com/contest/339/submission/16473859
https://codeforces.com/contest/339/submission/199345002
https://codeforces.com/contest/339/submission/161589547
https://codeforces.com/contest/339/submission/36226355
https://codeforces.com/contest/339/submission/167912806
https://codeforces.com/contest/339/submission/127866039
https://codeforces.com/contest/339/submission/149020440

##### After repeating the same code for the 4 dataframes and concatinating them

In [356]:
d = pd.read_csv('all_successful_submissions.csv')
d

              #  Number                                        Source_code
0     143163300     339  #include <bits/stdc++.h>\r\nusing namespace st...
1     160768387     339  #include <iostream>\r\n#include <bits/stdc++.h...
2     114785530     339  #include <iostream>\r\n#include <string.h>\r\n...
3      80016040     339  #include <bits/stdc++.h>\r\nusing namespace st...
4     105594767     339  #include<iostream>\r\nusing namespace std;\r\n...
...         ...     ...                                                ...
3875  161589547     339  #include<iostream>\r\nusing namespace std;\r\n...
3876   36226355     339  #include <bits/stdc++.h>\r\n\r\nusing namespac...
3877  167912806     339  #include<iostream>\r\n#include<vector>\r\nusin...
3878  127866039     339  /*"Perhaps..,we 're asking the wrong questions...
3879  149020440     339  #include<iostream>\r\n#include<string.h>\r\n#i...

[3880 rows x 3 columns]

In [357]:
friends_problemset_50_df

,#,When,Who,Language,Time,Memory,Problem_name,Number,Class,Number_Class,...,Tag_greedy,Tag_hashing,Tag_implementation,Tag_math,Tag_numbertheory,Tag_shortestpaths,Tag_sortings,Tag_specialproblem,Tag_strings,Tag_twopointers
0,164909440,Jul/19/2022 17:36,kinannotfound,GNU C++17,30Â ms,0Â KB,Watermelon,4,A,4A,...,0,0,0,1,0,0,0,0,0,0
1,168664652,Aug/17/2022 10:44,kinannotfound,GNU C++20 (64),30Â ms,0Â KB,Watermelon,4,A,4A,...,0,0,0,1,0,0,0,0,0,0
2,147200215,Feb/21/2022 20:13,obadaa.masri,GNU C++14,30Â ms,0Â KB,Watermelon,4,A,4A,...,0,0,0,1,0,0,0,0,0,0
3,172236866,Sep/15/2022 14:51,ShathaS2003,GNU C++17,30Â ms,0Â KB,Watermelon,4,A,4A,...,0,0,0,1,0,0,0,0,0,0
4,37352281,Apr/15/2018 14:50,samer_orfali,GNU C++,30Â ms,3200Â KB,Watermelon,4,A,4A,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3874,172442471,Sep/17/2022 13:21,ghina.alrefai,GNU C++20 (64),15Â ms,0Â KB,Pangram,520,A,520A,...,0,0,1,0,0,0,0,0,1,0
3875,195379716,Feb/28/2023 23:20,Wiaam_SA,GNU C++17,15Â ms,100Â KB,Pangram,520,A,520A,...,0,0,1,0,0,0,0,0,1,0
3876,181336513,Nov/17/2022 19:35,AbodeKu,GNU C++17,15Â ms,0Â KB,Pangram,520,A,520A,...,0,0,1,0,0,0,0,0,1,0
3877,68767582,Jan/14/2020 13:32,Brre.Hemo,GNU C++17,31Â ms,0Â KB,Pangram,520,A,520A,...,0,0,1,0,0,0,0,0,1,0
3878,109362084,Mar/08/2021 00:04,Brre.Hemo,GNU C++17,31Â ms,200Â KB,Pangram,520,A,520A,...,0,0,1,0,0,0,0,0,1,0

In [ ]:
friends_problemset_50_df.merge()

In [335]:
Problem_submissions_source_code_50_df = pd.read_csv('all_successful_submissions.csv')
Problem_submissions_source_code_50_df

              #  Number                                        Source_code
0     180723839     281  #include <bits/stdc++.h>\r\nusing namespace st...
1     114284635     281  #include <iostream>\r\n#include <string>\r\n\r...
2     130799045     281  #include <iostream>\r\n#include <string>\r\n\r...
3     171655748     281  #include<iostream>\r\nusing namespace std;\r\n...
4     196814219     281  #include <bits/stdc++.h>\r\nint main()\r\n{\r\...
...         ...     ...                                                ...
3875  162374843     580  #include <bits/stdc++.h>\r\n\r\nusing namespac...
3876  183474349     580  #include <bits/stdc++.h>\r\nusing namespace st...
3877  150303969     520  #include <iostream>\r\n#include <set>\r\nusing...
3878  172090257     520  #include <bits/stdc++.h>\r\n\r\nusing namespac...
3879  192212595     520  #include<bits/stdc++.h>\r\n\r\nusing namespace...

[3880 rows x 3 columns]

###### We noticed that there are one extra row

In [336]:
Problem_submissions_source_code_50_df.groupby(['#','Number']).count().reset_index().sort_values(by = 'Source_code')

              #  Number  Source_code
0       3499219      71            1
2577  168008066     486            1
2578  168019516     116            1
2579  168019697     231            1
2580  168056122     158            1
...         ...     ...          ...
1299  127270691     479            1
1300  127382360      58            1
1288  125927310     486            1
3878  209547047      58            1
3560  192996921     486            2

[3879 rows x 3 columns]

###### After comparing the values we found that they were the same but only different due to several attempts on scraping the website using endoing and without using it, so we deleted one of the repeated rows

In [337]:
# Delete rows where both '#' and 'Number' values are repeated
mask = Problem_submissions_source_code_50_df.duplicated(subset=['#', 'Number'], keep='first')
Problem_submissions_source_code_50_df = Problem_submissions_source_code_50_df[~mask]
Problem_submissions_source_code_50_df

              #  Number                                        Source_code
0     180723839     281  #include <bits/stdc++.h>\r\nusing namespace st...
1     114284635     281  #include <iostream>\r\n#include <string>\r\n\r...
2     130799045     281  #include <iostream>\r\n#include <string>\r\n\r...
3     171655748     281  #include<iostream>\r\nusing namespace std;\r\n...
4     196814219     281  #include <bits/stdc++.h>\r\nint main()\r\n{\r\...
...         ...     ...                                                ...
3875  162374843     580  #include <bits/stdc++.h>\r\n\r\nusing namespac...
3876  183474349     580  #include <bits/stdc++.h>\r\nusing namespace st...
3877  150303969     520  #include <iostream>\r\n#include <set>\r\nusing...
3878  172090257     520  #include <bits/stdc++.h>\r\n\r\nusing namespac...
3879  192212595     520  #include<bits/stdc++.h>\r\n\r\nusing namespace...

[3879 rows x 3 columns]

In [346]:
test = Problem_submissions_source_code_50_df.merge(friends_problemset_50_df, on = ['#', "Number"], how = 'left')
test
# # friends_problemset_50_df
# Problem_submissions_source_code_50_df

,#,Number,Source_code,When,Who,Language,Time,Memory,Problem_name,Class,...,Tag_greedy,Tag_hashing,Tag_implementation,Tag_math,Tag_numbertheory,Tag_shortestpaths,Tag_sortings,Tag_specialproblem,Tag_strings,Tag_twopointers
0,180723839,281,#include <bits/stdc++.h>\r\nusing namespace st...,Nov/13/2022 11:26,Mohammed_Abdelkareem,GNU C++17,30Â ms,0Â KB,Word Capitalization,A,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,114284635,281,#include <iostream>\r\n#include <string>\r\n\r...,Apr/26/2021 16:35,Lanakhaled,MS C++ 2017,60Â ms,0Â KB,Word Capitalization,A,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,130799045,281,#include <iostream>\r\n#include <string>\r\n\r...,Oct/04/2021 15:53,043_33798_Nuraiym-7,GNU C++17,30Â ms,3700Â KB,Word Capitalization,A,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,171655748,281,#include<iostream>\r\nusing namespace std;\r\n...,Sep/10/2022 23:38,Karam_mohmd,GNU C++17,30Â ms,0Â KB,Word Capitalization,A,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,196814219,281,#include <bits/stdc++.h>\r\nint main()\r\n{\r\...,Mar/10/2023 18:16,ghaith.clash88,GNU C++17 (64),30Â ms,0Â KB,Word Capitalization,A,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3874,162374843,580,#include <bits/stdc++.h>\r\n\r\nusing namespac...,Jun/30/2022 22:19,a7mad_taieb,GNU C++20 (64),218Â ms,400Â KB,Kefa and First Steps,A,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3875,183474349,580,#include <bits/stdc++.h>\r\nusing namespace st...,Dec/01/2022 15:17,7nooOoOoon,GNU C++17,187Â ms,400Â KB,Kefa and First Steps,A,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3876,150303969,520,#include <iostream>\r\n#include <set>\r\nusing...,Mar/20/2022 23:48,KHALED.TELLO,GNU C++17,15Â ms,100Â KB,Pangram,A,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3877,172090257,520,#include <bits/stdc++.h>\r\n\r\nusing namespac...,Sep/14/2022 02:44,M.Qattan,GNU C++17,15Â ms,100Â KB,Pangram,A,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3878,192212595,520,#include<bits/stdc++.h>\r\n\r\nusing namespace...,Feb/05/2023 01:12,7amzahsa,GNU C++20 (64),15Â ms,0Â KB,Pangram,A,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [347]:
rows_with_nan = test[pd.isna(test['Who'])]
rows_with_nan
# friends_problemset_50_df

,#,Number,Source_code,When,Who,Language,Time,Memory,Problem_name,Class,...,Tag_greedy,Tag_hashing,Tag_implementation,Tag_math,Tag_numbertheory,Tag_shortestpaths,Tag_sortings,Tag_specialproblem,Tag_strings,Tag_twopointers
988,206081570,486,import java.util.Scanner;\r\n\r\npublic class ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1006,37263341,200,"#include <stdio.h>\r\nint i,p,n,t;\r\nint main...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1038,35834183,200,#include<stdio.h>\r\n\r\nint main()\r\n{\r\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1057,195727139,200,import java.util.Scanner;\r\n\r\npublic class ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1065,201141908,200,import java.util.Objects;\r\nimport java.util....,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1078,201185098,318,"n, k = [int(i) for i in input().split()]\r\nan...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1083,35571065,318,#include <stdio.h>\r\n\r\nint main()\r\n{\r\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1102,110032147,318,#include<cmath>\r\n#include<iostream>\r\n#incl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1172,35574382,61,#include <stdio.h>\r\n\r\nint main()\r\n{\r\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1212,201186461,133,s = input()\r\nno = True\r\nfor i in s:\r\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1241,35482863,133,#include <stdio.h>\r\n#include <string.h>\r\n\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1264,75054968,133,import java.util.Scanner;\r\n\r\npublic class ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1272,37263197,705,"#include <stdio.h>\r\nchar*a[]={""I hate that"",...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1293,28335487,705,#include <stdio.h>\r\n#include <stdlib.h>\r\n\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1301,158150229,705,fun main() {\r\n \r\n var n : Int = read...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1368,35651968,228,#include <stdio.h>\r\n\r\nint main()\r\n{\r\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1399,201314877,405,n = int(input())\r\na = [int(i) for i in input...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1466,35578453,405,#include <stdio.h>\r\n\r\nint main()\r\n{\r\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1519,35571950,469,#include <stdio.h>\r\n\r\nint main()\r\n{\r\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1532,178272281,469,import java.util.Scanner;\r\n\r\n\r\npublic cl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1591,35545803,479,#include <stdio.h>\r\n\r\nint main()\r\n{\r\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1643,138134933,1328,import java.util.Scanner;\r\n\r\npublic class ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1685,35572422,144,#include <stdio.h>\r\n\r\nint main()\r\n{\r\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1712,35535134,144,#include <stdio.h>\r\n#include <stdlib.h>\r\n\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1722,25346186,148,#include <stdio.h>\r\nint main()\r\n{\r\nint k...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1748,158197199,148,fun main() {\r\n \r\n var k : Int = read...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1762,35533586,148,#include <stdio.h>\r\nint cmpfunc (const void ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1778,201330483,580,n = int(input())\r\na = [int(i) for i in input...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1787,28883115,580,#include <stdio.h>\r\n#include <stdlib.h>\r\ni...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1793,35533931,580,#include <stdio.h>\r\n\r\nint main()\r\n{\r\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1822,178445664,520,count = 0\r\nnum = int(input())\r\nif num < 26...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1824,35649819,520,#include <stdio.h>\r\n#include <string.h>\r\ni...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1864,35568898,520,#include<stdio.h>\r\n\r\nint main()\r\n{\r\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2557,48061867,1030,#include<stdio.h>\r\n\r\n\r\nint main()\r\n{\r...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2575,201135325,1030,import java.util.Scanner;\r\nimport java.util...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2576,194568513,1030,import javax.lang.model.type.NullType;\r\nimpo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2580,201161120,160,sum1 = 0\r\nsum2 = 0\r\nn = int(input())\r\na ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2616,35516335,160,#include <stdio.h>\r\n\r\nint main()\r\n{\r\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2626,35432672,160,#include <stdio.h>\r\n#include <stdlib.h>\r\n\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2666,35530387,467,#include <stdio.h>\r\n\r\nint main()\r\n{\r\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2698,75053676,467,import java.util.Scanner;\r\npublic class Main...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2726,46987734,344,#include <stdio.h>\r\n\r\nint main()\r\n{\r\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2727,35573936,344,#include <stdio.h>\r\n\r\nint main()\r\n{\r\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2735,35610868,344,#include<stdio.h>\r\n\r\nint main()\r\n{\r\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2750,106236142,344,import java.util.Scanner;\r\npublic class Main...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2770,75072619,344,import java.util.Scanner;\r\npublic class Main...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2806,35546680,136,#include <stdio.h>\r\n\r\nint main()\r\n{\r\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2850,74822204,136,import java.util.Scanner;\r\n\r\npublic class ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2855,178402791,486,sum = 0\r\nnum = int(input())\r\nif num % 2 ==...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [300]:
if os.path.exists('failed_submission.csv'):
    failed_submission = pd.read_csv("failed_submission.csv")
    
    # Find the index where starting_point['#'] is equal to the specific value
    start_index = rows_with_nan[rows_with_nan['#'] == failed_submission['#'][0]].index[0]
    # start_index = friends_problemset_50_df2[friends_problemset_50_df2['#'] == 148496259].index[0]

    # Slice the DataFrame to include rows starting from the identified index
    starting_point = rows_with_nan.loc[start_index:]
    os.remove('failed_submission.csv')

else:
    # start_index = friends_problemset_50_df2[friends_problemset_50_df2['#'] == 148496259].index[0]
    # starting_point = friends_problemset_50_df3.loc[start_index:]
    # os.remove('failed_submission.csv')
    starting_point = rows_with_nan
    

# Iterate over the values in 'Number' and '#' columns
for num, submission in zip(starting_point['Number'], starting_point['#']):
        # The base URL for the submission page
        try:
            submission_url = f'https://codeforces.com/contest/{num}/submission/{submission}'
            print(submission_url)

            # Send a GET request to the URL
            response = requests.get(submission_url)

            # Check if the request was successful
            if response.status_code == 200:
                # Parse the HTML content using BeautifulSoup
                soup = BeautifulSoup(response.content, 'html.parser')

                # Find the element containing the source code
                source_elem = soup.select('#program-source-text')

                # Check if the element was found
                if source_elem:
                    # Convert the HTML source code to plain text
                    source = html.unescape(source_elem[0].decode_contents())

                    # Path to the successful_submission file
                    successful_submissions = "all_successful_submissions.csv"

                    # Open the file in append mode and write the data
                    with open(successful_submissions, "a", newline="", encoding='utf-8') as file:
                        writer = csv.DictWriter(file, fieldnames=["#", "Number", 'Source_code'])

                        # Write the header row if the file is empty
                        if file.tell() == 0:
                            writer.writeheader()

                        # Append the data rows
                        writer.writerows([{"#": submission, "Number": num, "Source_code":source}])
                else:
                    print(f'Failed to find source code for submission {submission} in contest {num}')

                    # Path to the failed_submission.csv file
                    failed_submission = "failed_submission.csv"

                    # Open the file in append mode and write the data
                    with open(failed_submission, "w", newline="", encoding='utf-8') as file:
                        writer = csv.DictWriter(file, fieldnames=["#", "Number"])

                        # Write the header row if the file is empty
                        if file.tell() == 0:
                            writer.writeheader()

                        # Append the data rows
                        writer.writerows([{"#": submission, "Number": num}])

                    winsound.PlaySound('frog.wav', winsound.SND_FILENAME)
                    break

            else:
                print(f'Failed to retrieve submission {submission} in contest {num}')
            time.sleep(2)

        except requests.exceptions.RequestException as e:
            print(f'Connection Error: {str(e)}')
            failed_submission = "failed_submission.csv"
            # Open the file in append mode and write the data
            with open(failed_submission, "w", newline="", encoding='utf-8') as file:
                writer = csv.DictWriter(file, fieldnames=["#", "Number"])
                # Write the header row if the file is empty
                if file.tell() == 0:
                    writer.writeheader()

                # Append the data rows
                writer.writerows([{"#": submission, "Number": num}])

            winsound.PlaySound('frog.wav', winsound.SND_FILENAME)
            break

https://codeforces.com/contest/1030/submission/148299570
https://codeforces.com/contest/160/submission/166105956
https://codeforces.com/contest/160/submission/166104617
https://codeforces.com/contest/160/submission/175454823
https://codeforces.com/contest/160/submission/172967508
https://codeforces.com/contest/160/submission/112189003
https://codeforces.com/contest/467/submission/199232726
https://codeforces.com/contest/344/submission/166909069
https://codeforces.com/contest/344/submission/28915840
https://codeforces.com/contest/344/submission/34525911
https://codeforces.com/contest/344/submission/152799498
https://codeforces.com/contest/344/submission/182286722
https://codeforces.com/contest/344/submission/48092614
https://codeforces.com/contest/136/submission/16649378
https://codeforces.com/contest/486/submission/104621886
https://codeforces.com/contest/486/submission/185924829
https://codeforces.com/contest/486/submission/79624850
https://codeforces.com/contest/200/submission/34003964
https://codeforces.com/contest/200/submission/68561094
https://codeforces.com/contest/200/submission/153116881
https://codeforces.com/contest/200/submission/153835148
https://codeforces.com/contest/318/submission/159930473
https://codeforces.com/contest/318/submission/70744068
https://codeforces.com/contest/318/submission/173802299
https://codeforces.com/contest/61/submission/181762096
https://codeforces.com/contest/133/submission/158915512
https://codeforces.com/contest/133/submission/56687163
https://codeforces.com/contest/705/submission/167129082
https://codeforces.com/contest/705/submission/159312178
https://codeforces.com/contest/705/submission/167792561
https://codeforces.com/contest/705/submission/159375020
https://codeforces.com/contest/228/submission/174019476
https://codeforces.com/contest/405/submission/148267376
https://codeforces.com/contest/469/submission/167436982
https://codeforces.com/contest/469/submission/169838839
https://codeforces.com/contest/469/submission/167989186
https://codeforces.com/contest/1328/submission/168291048
https://codeforces.com/contest/1328/submission/74405188
https://codeforces.com/contest/144/submission/75285381
https://codeforces.com/contest/144/submission/153828665
https://codeforces.com/contest/148/submission/72585234
https://codeforces.com/contest/148/submission/162230469
https://codeforces.com/contest/148/submission/193435563
https://codeforces.com/contest/580/submission/36421933
https://codeforces.com/contest/580/submission/162374843
https://codeforces.com/contest/580/submission/183474349
https://codeforces.com/contest/520/submission/150303969
https://codeforces.com/contest/520/submission/172090257
https://codeforces.com/contest/520/submission/192212595

# To be deleted
## Add the code from Sarah's notebook instead of reading the file top_friends_all_problemset_df

### Preprocessing

In [155]:
top_friends_problems_df = pd.read_csv("top_friends_all_problemset_df.csv")
top_friends_problems_df

,#,When,Who,Problem_name,Number,Character
0,209681722,Jun/14/2023 18:38,kinannotfound,Keep it Beautiful,1841,B
1,209597019,Jun/13/2023 20:48,kinannotfound,Keep it Beautiful,1841,B
2,209489090,Jun/12/2023 21:52,kinannotfound,Game with Board,1841,A
3,209209772,Jun/10/2023 18:37,kinannotfound,Ski Resort,1840,C
4,209181412,Jun/10/2023 13:14,kinannotfound,Running Miles,1826,D
...,...,...,...,...,...,...
35986,148525935,Mar/06/2022 09:54,7amzahsa,Watermelon,4,A
35987,148500169,Mar/06/2022 00:11,7amzahsa,QAQ,894,A
35988,148495708,Mar/05/2022 22:46,7amzahsa,Case of the Zeros and Ones,556,A
35989,148491387,Mar/05/2022 21:32,7amzahsa,Bear and Big Brother,791,A
35990,148490756,Mar/05/2022 21:24,7amzahsa,Next Round,158,A

###### First,
1. One submission per student on a problem:
 
 ##### We don't need multiple problems submissions by the student, so we will keep only the oldest submission in date

In [156]:
top_friends_problems_df['When'] = pd.to_datetime(top_friends_problems_df['When'])  # Convert 'When' column to datetime

sorted_top_friends_problems_df = top_friends_problems_df.sort_values('When')  # Sort DataFrame by 'When' column in ascending order

mask = sorted_top_friends_problems_df.duplicated(['Who','Problem_name'], keep='first')  # Create mask to keep the older row for each unique 'Character' value

top_friends_problems_df = sorted_top_friends_problems_df[~mask]
top_friends_problems_df

,#,When,Who,Problem_name,Number,Character
22303,16293842,2016-02-23 17:11:00,Mohammad_Kartoumeh,Again Twenty Five!,630,A
22302,16315285,2016-02-24 22:02:00,Mohammad_Kartoumeh,Cinema Line,349,A
22301,16329705,2016-02-25 15:04:00,Mohammad_Kartoumeh,Theatre Square,1,A
22299,16330205,2016-02-25 15:37:00,Mohammad_Kartoumeh,Bit++,282,A
22298,16336538,2016-02-25 22:19:00,Mohammad_Kartoumeh,Watermelon,4,A
...,...,...,...,...,...,...
6365,209730119,2023-06-15 10:04:00,OmranMk,Round 1,104147,A
6364,209731196,2023-06-15 10:18:00,OmranMk,I'll call him Hanya,104147,B
6363,209731969,2023-06-15 10:26:00,OmranMk,Hobz is a good guy,104147,K
6362,209734375,2023-06-15 10:52:00,OmranMk,Nesr El Sieve,104147,F
33374,209741019,2023-06-15 11:54:00,IT-24-,Abo Abdo Smoothies,104426,H

##### Second
2. Only problems submissions before last submission on the problemset
#### We don't need the problems solved by students that their submission's date is after the date of their last submission on the problemset

In [172]:
friends_problemset_50_df.head()

,#,When,Who,Language,Verdict,Time,Memory,Problem_name,Number,Character,Number_Character,Name,Difficulty,Solved
0,164909440,Jul/19/2022 17:36,kinannotfound,GNU C++17,Accepted,30Â ms,0Â KB,Watermelon,4,A,4A,Watermelon \n\n\nbrute forc...,800,x394103
1,168664652,Aug/17/2022 10:44,kinannotfound,GNU C++20 (64),Accepted,30Â ms,0Â KB,Watermelon,4,A,4A,Watermelon \n\n\nbrute forc...,800,x394103
2,147200215,Feb/21/2022 20:13,obadaa.masri,GNU C++14,Accepted,30Â ms,0Â KB,Watermelon,4,A,4A,Watermelon \n\n\nbrute forc...,800,x394103
3,172236866,Sep/15/2022 14:51,ShathaS2003,GNU C++17,Accepted,30Â ms,0Â KB,Watermelon,4,A,4A,Watermelon \n\n\nbrute forc...,800,x394103
4,37352281,Apr/15/2018 14:50,samer_orfali#,GNU C++,Accepted,30Â ms,3200Â KB,Watermelon,4,A,4A,Watermelon \n\n\nbrute forc...,800,x394103

In [175]:
friends_problemset_50_df['When'] = pd.to_datetime(friends_problemset_50_df['When']) 
last_friends_problemset_50_submission_dates_df = friends_problemset_50_df.groupby('Who')['When'].max().reset_index()
last_friends_problemset_50_submission_dates_df

                      Who                When
0         * Baraa_Armoush 2020-03-26 17:37:00
1              * Kavaliro 2020-03-26 17:38:00
2    * Mohammad_Kartoumeh 2018-05-06 17:09:00
3        * RedNextCentury 2020-03-26 17:35:00
4          * SaeedSabbagh 2020-03-26 17:38:00
..                    ...                 ...
134         sarah.m.akkad 2023-02-22 23:53:00
135               sepsa.m 2020-03-22 16:26:00
136              sepsa.m# 2020-03-26 21:15:00
137           sidratello9 2022-11-17 23:50:00
138           yaser.harba 2021-11-03 13:37:00

[139 rows x 2 columns]

### Features Engineering

1) Feature's name: Previous_problems_count
##### we want to create a feature for each student that represents the problems number he solved before each problem in the problemset

In [150]:
friends_problemset_source_code_df['When'] = pd.to_datetime(filtered_df['When']) 

sorted_friends_problemset_source_code_df = friends_problemset_source_code_df.sort_values('When')  # Sort DataFrame by 'When' column in ascending order

friends_problems_before_problemset = friends_problems_before_problemset.to_datetime(filtered_df['When'])



mask = sorted_df.duplicated(['Who','Problem_name'], keep='last')  # Create mask to keep the older row for each unique 'Character' value

filtered_df2 = sorted_df[~mask] 
filtered_df2

NameError: name 'filtered_df' is not defined

### Baseline: Simple Linear Regression

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


linreg = LinearRegression().fit(X_train, y_train)

In [ ]:
print('Codeforces dataset')
print('linear model intercept: {}'
     .format(linreg.intercept_))
print('linear model coeff:\n{}'
     .format(linreg.coef_))
print('R-squared score (training): {:.3f}'
     .format(linreg.score(X_train, y_train)))
print('R-squared score (test): {:.3f}'
     .format(linreg.score(X_test, y_test)))

### Dummy regressors

# FOR DELETION (WE CAN TRY APPLYING MULTIPLE OPTIONS)
strategy parameter options:
- mean : predicts the mean of the training targets.
- median : predicts the median of the training targets.
- quantile : predicts a user-provided quantile of the training target values (e.g. value at the 75th percentile)
- constant : predicts a constant user-provided value.

In [ ]:
# - Alternative metrics include:
#     - mean_absolute_error (absolute difference of target & predicted values)
#     - mean_squared_error (squared difference of target & predicted values)
    
lm_dummy_mean = DummyRegressor(strategy = 'mean').fit(X_train, y_train)

y_predict = linreg.predict(X_test)
y_predict_dummy_mean = lm_dummy_mean.predict(X_test)

print('Linear model, coefficients: ', linreg.coef_)
print("Mean squared error (dummy): {:.2f}".format(mean_squared_error(y_test, 
                                                                     y_predict_dummy_mean)))
print("Mean squared error (linear model): {:.2f}".format(mean_squared_error(y_test, y_predict)))
print("r2_score (dummy): {:.2f}".format(r2_score(y_test, y_predict_dummy_mean)))
print("r2_score (linear model): {:.2f}".format(r2_score(y_test, y_predict)))

# Plot outputs
plt.scatter(X_test, y_test,  color='black')
plt.plot(X_test, y_predict, color='green', linewidth=2)
plt.plot(X_test, y_predict_dummy_mean, color='red', linestyle = 'dashed', 
         linewidth=2, label = 'dummy')

plt.show()

### Scaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)

In [ ]:
X_test_scaled = scaler.transform(X_test)

### Ridge regression

In [ ]:
from sklearn.linear_model import Ridge

linridge = Ridge(alpha=20.0).fit(X_train, y_train)

print('Codeforces dataset')
print('ridge regression linear model intercept: {}'
     .format(linridge.intercept_))
print('ridge regression linear model coeff:\n{}'
     .format(linridge.coef_))
print('R-squared score (training): {:.3f}'
     .format(linridge.score(X_train, y_train)))
print('R-squared score (test): {:.3f}'
     .format(linridge.score(X_test, y_test)))
print('Number of non-zero features: {}'
     .format(np.sum(linridge.coef_ != 0)))

#### Ridge regression with regularization parameter: alpha

In [ ]:
# Do NOT forget to discuss several alpha values

print('Ridge regression: effect of alpha regularization parameter\n')
all_alphas = [0, 1, 10, 20, 50, 100, 1000]
all_r2_train = []
all_r2_test = []
for this_alpha in all_alphas:
    linridge = Ridge(alpha = this_alpha).fit(X_train_scaled, y_train)
    r2_train = linridge.score(X_train_scaled, y_train)
    all_r2_train.append(r2_train)
    r2_test = linridge.score(X_test_scaled, y_test)
    all_r2_test.append(r2_test)
    num_coeff_bigger = np.sum(abs(linridge.coef_) > 1.0)
    
    print('Alpha = {:.2f}\nnum abs(coeff) > 1.0: {}, \
r-squared training: {:.2f}, r-squared test: {:.2f}\n'
         .format(this_alpha, num_coeff_bigger, r2_train, r2_test))

In [ ]:
plt.figure(figsize=(5,4))
alphas = all_alphas
plt.scatter(alphas, all_r2_train, marker= 'o', s=50, alpha=0.8)
plt.scatter(alphas, all_r2_test, marker= 'x', s=50, alpha=0.8)
plt.title('R2 Error Over Different Alphas')
plt.xlabel('alpha values')
plt.ylabel('r2 error')
plt.show()

### Lasso regression

In [ ]:
print('Lasso regression: effect of alpha regularization\n\
parameter on number of features kept in final model\n')

linlasso = Lasso(alpha, max_iter = 10000).fit(X_train, y_train)

print('Codeforces dataset')
print('lasso regression linear model intercept: {}'
     .format(linlasso.intercept_))
print('lasso regression linear model coeff:\n{}'
     .format(linlasso.coef_))
print('R-squared score (training): {:.3f}'
     .format(linlasso.score(X_train, y_train)))
print('R-squared score (test): {:.3f}'
     .format(linlasso.score(X_test, y_test)))
print('Number of non-zero features: {}'
     .format(np.sum(linridge.coef_ != 0)))

#### Lasso regression with regularization parameter: alpha

In [ ]:
print('Lasso regression: effect of alpha regularization\n\
parameter on number of features kept in final model\n')
all_alphas = [0.5, 1, 2, 3, 5, 10, 20, 50]
all_r2_train = []
all_r2_test = []
for alpha in all_alphas:
    linlasso = Lasso(alpha, max_iter = 10000).fit(X_train_scaled, y_train)
    r2_train = linlasso.score(X_train_scaled, y_train)
    r2_test = linlasso.score(X_test_scaled, y_test)
    all_r2_train.append(r2_train)
    all_r2_test.append(r2_test)
    
    print('Alpha = {:.2f}\nFeatures kept: {}, r-squared training: {:.2f}, \
r-squared test: {:.2f}\n'
         .format(alpha, np.sum(linlasso.coef_ != 0), r2_train, r2_test))

In [ ]:
plt.figure(figsize=(5,4))
alphas = all_alphas
plt.scatter(alphas, all_r2_train, marker= 'o', s=50, alpha=0.8)
plt.scatter(alphas, all_r2_test, marker= 'x', s=50, alpha=0.8)
plt.title('R2 Error Over Different Alphas')
plt.xlabel('alpha values')
plt.ylabel('r2 error')
plt.show()

### KNN

# TO BE DELETED

With regression, **what we do is instead of taking a majority vote, we don't have class values here as targets, we have continuous values. So we can average these  target values. And if we do that, we find that the output, when the query point is this X-value, is going to be the average of the y-values of the three nearest training points**.


**KNeighborsRegressor: important parameters**
- Model complexity: n_neighbors: number of nearest neighbors (k) to considerâ€“Default  = 5
- Model fitting: metric:  distance function between data pointsâ€“Default: Minkowski distance with power parameter p = 2 (Euclidean)

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

knnreg = KNeighborsRegressor(n_neighbors = 5).fit(X_train, y_train)

print(knnreg.predict(X_test))
print('R-squared test score: {:.3f}'
     .format(knnreg.score(X_test, y_test)))

In [ ]:
fig, subaxes = plt.subplots(1, 2, figsize=(8,4))
X_predict_input = np.linspace(-3, 3, 50).reshape(-1,1)
X_train, X_test, y_train, y_test = train_test_split(X_R1[0::5], y_R1[0::5], random_state = 0)

for thisaxis, K in zip(subaxes, [1, 3]):
    knnreg = KNeighborsRegressor(n_neighbors = K).fit(X_train, y_train)
    y_predict_output = knnreg.predict(X_predict_input)
    thisaxis.set_xlim([-2.5, 0.75])
    thisaxis.plot(X_predict_input, y_predict_output, '^', markersize = 10,
                 label='Predicted', alpha=0.8)
    thisaxis.plot(X_train, y_train, 'o', label='True Value', alpha=0.8)
    thisaxis.set_xlabel('Input feature')
    thisaxis.set_ylabel('Target value')
    thisaxis.set_title('KNN regression (K={})'.format(K))
    thisaxis.legend()
plt.tight_layout()

### Regression model complexity as a function of K

In [ ]:
# plot k-NN regression on sample dataset for different values of K
fig, subaxes = plt.subplots(5, 1, figsize=(5,20))
X_predict_input = np.linspace(-3, 3, 500).reshape(-1,1)
X_train, X_test, y_train, y_test = train_test_split(X_R1, y_R1,
                                                   random_state = 0)

for thisaxis, K in zip(subaxes, [1, 3, 7, 15, 55]):
    knnreg = KNeighborsRegressor(n_neighbors = K).fit(X_train, y_train)
    y_predict_output = knnreg.predict(X_predict_input)
    train_score = knnreg.score(X_train, y_train)
    test_score = knnreg.score(X_test, y_test)
    thisaxis.plot(X_predict_input, y_predict_output)
    thisaxis.plot(X_train, y_train, 'o', alpha=0.9, label='Train')
    thisaxis.plot(X_test, y_test, '^', alpha=0.9, label='Test')
    thisaxis.set_xlabel('Input feature')
    thisaxis.set_ylabel('Target value')
    thisaxis.set_title('KNN Regression (K={})\n\
Train $R^2 = {:.3f}$,  Test $R^2 = {:.3f}$'
                      .format(K, train_score, test_score))
    thisaxis.legend()
    plt.tight_layout(pad=0.4, w_pad=0.5, h_pad=1.0)

# TO BE DELETED
Starting on the left when k = 1, the regression model fits the training data perfectly with a r-squared score of 1.0. But it's very bad at predicting the target values for new data samples, as reflected in the r-squared test score of only 0.155. As the value of k increases, which we can see acts to smooth out these local variations to capture more of the global trend. 

Again the training set score drops, but the model gets better at generalizing to new data and the test score goes up as K increases. Finally in this series, the model with k = 15 has the best test set performance, with an r-squared score of 0.485. Increasing k much further however to k = 55, results in both the training and test set scores dropping back down to lower levels, as the model now starts to under-fit. In other words, it's too simple to do well, even on the training data. 

#### When to use KNN
The pro's of the nearest neighbor approach are that it's simple and easy to understand why a particular prediction is made. A k-nearest neighbor approach can be a reasonable baseline against what you can compare more sophisticated methods. 

When the training data has many instances, or each instance has lots of features, this can really slow down the performance of a k-nearest neighbors model. So in general, if your data set has hundreds or thousands of features, you should consider alternatives to k-nearest neighbors models, especially if your data is sparse. Meaning that each instance has lots of features, but most of them are zero.

In [ ]:
- Alternative metrics include:
    - mean_absolute_error (absolute difference of target & predicted values)
    - mean_squared_error (squared difference of target & predicted values)