In [ ]:
!pip install requests_ip_rotator

In [4]:
# importing libraries
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.dummy import DummyRegressor
import pandas as pd
import html
import time
import csv
# from scrapy.downloadermiddlewares.retry import RetryMiddleware
# from scrapy_random_proxies.middlewares import RandomProxyMiddleware
import requests
from bs4 import BeautifulSoup
import random
from requests_ip_rotator import ApiGateway, EXTRA_REGIONS

import os

In [47]:
# Send GET request to the page
url = 'https://codeforces.com/submissions/{}'
response = requests.get(url)

friend_name = 'abbas.az408'

# Make a GET request to the submission URL with the contest ID and submission ID
response = requests.get(url.format(friend_name))

# Check if the request was successful
if response.status_code == 200:
    # Parse the HTML content using BeautifulSoup
    soup = BeautifulSoup(response.content, 'html.parser')

# Find the submissions table
table = soup.find('table', {'class': 'status-frame-datatable'})
if table is None:
    print("Error: Submissions table not found")
    exit()

# Extract all rows in the table
data = []
header = ['#','Who', 'Number']

for row in table.find_all('tr'):
    cols = row.find_all('td')
    if len(cols) > 0:
        if cols[5].text.strip()=='Accepted':
          # print(cols[5].text.strip()=='Accepted')
          # print(cols[3].text.split('-')[1].strip())
          num = row.find_all('td', class_="status-small")[1].find('a')['href'].split('/')[2]
          # print(num)
          submission = cols[0].text.strip()
        # row_data = [col.text.strip() for col in cols]
          data.append([submission, friend_name, num])
#         rows.append(row_data)

# Create a pandas DataFrame from the rows
df = pd.DataFrame(data[1:], columns=header)

# Print the DataFrame
df

           #          Who Number
0  206364516  abbas.az408   1829
1  204881246  abbas.az408   1829
2  204876042  abbas.az408   1829
3  204861328  abbas.az408   1829
4  203762892  abbas.az408   1033
5  199333045  abbas.az408    231
6  199328431  abbas.az408     71
7  197542824  abbas.az408      4
8  197512762  abbas.az408      4
9  197512320  abbas.az408      4